---
- name: Setup K3s on Minecraft Server VM
  hosts: App_vm
  become: true
  tasks:
    - name: Install K3s (Master Node)
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Change k3s.yaml permission
      file:
        path: /etc/rancher/k3s/k3s.yaml
        mode: '0644' # 一般ユーザーでもkubectlを見れるようにする
